### ISSUE TITLE
Windows 11 click "Load file fystem from device" Exception

### ISSUE THREAD

**Issue by ginokai** [unsound/hfsexplorer#29]
Debug Console:
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: org.catacombae.storage.io.win32.ReadableWin32FileStream.openNative(Ljava/lang/String;)[B
	at org.catacombae.storage.io.win32.ReadableWin32FileStream.openNative(Native Method)
	at org.catacombae.storage.io.win32.ReadableWin32FileStream.open(ReadableWin32FileStream.java:319)
	at org.catacombae.storage.io.win32.ReadableWin32FileStream.<init>(ReadableWin32FileStream.java:138)
	at org.catacombae.hfsexplorer.SelectDeviceDialog$Windows.createStream(SelectDeviceDialog.java:739)
	at org.catacombae.hfsexplorer.SelectDeviceDialog$Windows.detectDevices(SelectDeviceDialog.java:784)
	at org.catacombae.hfsexplorer.SelectDeviceDialog.refreshDevices(SelectDeviceDialog.java:206)
	at org.catacombae.hfsexplorer.SelectDeviceDialog.<init>(SelectDeviceDialog.java:131)
	at org.catacombae.hfsexplorer.SelectDeviceDialog$Windows.<init>(SelectDeviceDialog.java:734)
	at org.catacombae.hfsexplorer.SelectDeviceDialog$WindowsFactory.createDeviceDialog(SelectDeviceDialog.java:726)
	at org.catacombae.hfsexplorer.SelectDeviceDialog.createSelectDeviceDialog(SelectDeviceDialog.java:314)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow$4.actionPerformed(FileSystemBrowserWindow.java:230)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by unsound** [comment]
Did you intend to close this? If so, then could you share the solution to your problem?
I could never reproduce it so if you're still having this issue I would urge you to try to reinstall Java or use a newer Java version.
