### ISSUE TITLE
com.apple.eawt.ApplicationListener is Deprecated

### ISSUE THREAD

**Issue by johnothwolo** [unsound/hfsexplorer#45]
As shown [here](https://stackoverflow.com/questions/9239287/what-is-the-alternative-for-deprecated-com-apple-eawt-applicationlistener), some APIs are deprecated on macOS.

```
System L&F class name: com.apple.laf.AquaLookAndFeel
Exception in thread "main" java.lang.RuntimeException: java.lang.ClassNotFoundException: com.apple.eawt.ApplicationListener
	at org.catacombae.hfsexplorer.MacUtil.registerMacApplicationHandler(MacUtil.java:83)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.<init>(FileSystemBrowserWindow.java:167)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.<init>(FileSystemBrowserWindow.java:154)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.openFileSystemBrowserWindow(FileSystemBrowserWindow.java:3252)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.main(FileSystemBrowserWindow.java:3304)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.ApplicationListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.catacombae.hfsexplorer.MacUtil.registerMacApplicationHandlerInternal(MacUtil.java:93)
	at org.catacombae.hfsexplorer.MacUtil.registerMacApplicationHandler(MacUtil.ja
	... 4 more
```

**Comment by VyrCossont** [comment]
It looks like alternatives were introduced in 2012:

> Please migrate to using the com.apple.eawt.Application.set\*Handler() APIs if you want to hook into Open, Preferences, About, Quit menu items / events.
— archived Apple mailing list message quoted on https://stackoverflow.com/a/28090946

`com.apple.eawt.Application` and its Handler methods seems to still exist on JDK 19 under macOS 14; I'm going to try to substitute those when available.

**Comment by VyrCossont** [comment]
Alternatively, patching `org.catacombae.hfsexplorer.MacUtil.isMacOSX` to always return `false` will get you going by skipping the few Mac-specific features.

**Comment by unsound** [comment]
AFAIK this was already fixed in https://github.com/unsound/hfsexplorer/commit/bffdea7734e22720606a5c2b652d32ec7cb86c9d .

**Comment by VyrCossont** [comment]
Missed that. Thank you!

**Comment by johnothwolo** [comment]
It appears the last release was made before the fix.
