### ISSUE TITLE
unable to open encrypted .dmg in windows with hfsexplorer

### ISSUE THREAD

**Issue by spk911k** [unsound/hfsexplorer#46]
Could not open file! Exception thrown:
org.catacombae.dmgextractor.DmgException: Invalid zlib data!
	at org.catacombae.dmg.udif.UDIFBlockInputStream$ZlibBlockInputStream.fillBuffer(UDIFBlockInputStream.java:282)
	at org.catacombae.dmg.udif.UDIFBlockInputStream.read(UDIFBlockInputStream.java:156)
	at org.catacombae.dmg.udif.UDIFRandomAccessStream.read(UDIFRandomAccessStream.java:143)
	at org.catacombae.io.SynchronizedReadableRandomAccessStream.read(SynchronizedReadableRandomAccessStream.java:209)
	at org.catacombae.io.SynchronizedReadableRandomAccessStream.readFrom(SynchronizedReadableRandomAccessStream.java:102)
	at org.catacombae.io.ReadableRandomAccessSubstream.read(ReadableRandomAccessSubstream.java:82)
	at org.catacombae.io.SynchronizedReadableRandomAccessStream.read(SynchronizedReadableRandomAccessStream.java:209)
	at org.catacombae.io.SynchronizedReadableRandomAccessStream.readFrom(SynchronizedReadableRandomAccessStream.java:102)
	at org.catacombae.io.ReadableRandomAccessSubstream.read(ReadableRandomAccessSubstream.java:82)
	at org.catacombae.io.BasicReadable.readFully(BasicReadable.java:68)
	at org.catacombae.io.BasicReadable.readFully(BasicReadable.java:59)
	at org.catacombae.storage.ps.gpt.types.GUIDPartitionTable.<init>(GUIDPartitionTable.java:105)
	at org.catacombae.storage.ps.gpt.GPTHandler.readPartitionTable(GPTHandler.java:58)
	at org.catacombae.storage.ps.gpt.GPTHandler.getPartitions(GPTHandler.java:45)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.loadFS(FileSystemBrowserWindow.java:1003)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.loadFSWithUDIFAutodetect(FileSystemBrowserWindow.java:940)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.loadFSWithUDIFAutodetect(FileSystemBrowserWindow.java:802)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow.loadFSWithUDIFAutodetect(FileSystemBrowserWindow.java:778)
	at org.catacombae.hfsexplorer.FileSystemBrowserWindow$5.actionPerformed(FileSystemBrowserWindow.java:345)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.util.zip.DataFormatException: incorrect header check
	at java.util.zip.Inflater.inflateBytes(Native Method)
	at java.util.zip.Inflater.inflate(Unknown Source)
	at org.catacombae.dmg.udif.UDIFBlockInputStream$ZlibBlockInputStream.fillBuffer(UDIFBlockInputStream.java:268)
	... 56 more

**Comment by unsound** [comment]
Since the error message is "invalid zlib data" it may be that the dmg file is corrupted. Given the nature of the error I don't think it's fixable by us, however it's possible to recovering from this error is possible, and that would be a feature request.
@spk911k if you still have this dmg file laying around, could you share it somehow? (Privately via email is fine.)

**Comment by unsound** [comment]
Note: Slightly related to #44.
